Repository jsk-ros-pkg/jsk_visualization, pull requests merged in 2020-10, with the labels that each got.

#771 call processNormal when polygon points has more than 3 point
  jsk_rviz_plugins/src/polygon_array_display.cpp
Labels: bug

#750 Remove meaningless lock
  jsk_interactive_markers/jsk_interactive_marker/src/bounding_box_marker.cpp
  jsk_interactive_markers/jsk_interactive_marker/src/interactive_point_cloud.cpp
  jsk_interactive_markers/jsk_interactive_marker/src/polygon_marker.cpp
  jsk_interactive_markers/jsk_interactive_marker/src/urdf_model_marker.cpp
  jsk_rviz_plugins/src/overlay_diagnostic_display.cpp
  jsk_rviz_plugins/src/overlay_image_display.cpp
Labels: question

#782 [jsk_rviz_plugin/PieChart] add clock wise rotate option for pie chart
  jsk_rviz_plugins/src/pie_chart_display.cpp
  jsk_rviz_plugins/src/pie_chart_display.h
Labels: enhancement

#728 [jsk_rviz_plugins] Add StringDisplay as a new display plugin
  doc/jsk_rviz_plugins/plugins/images/string.png
  doc/jsk_rviz_plugins/plugins/string.md
  jsk_rviz_plugins/CMakeLists.txt
  jsk_rviz_plugins/cfg/overlay_sample.rviz
  jsk_rviz_plugins/launch/overlay_sample.launch
  jsk_rviz_plugins/plugin_description.xml
  jsk_rviz_plugins/src/string_display.cpp
  jsk_rviz_plugins/src/string_display.h
Labels: feature

#776 Add fg_color/bg_color to OverlayMenu.msg
  jsk_rviz_plugins/msg/OverlayMenu.msg
Labels: feature

#775 Support custom color for OverlayMenu
  jsk_rviz_plugins/cfg/overlay_sample.rviz
  jsk_rviz_plugins/samples/overlay_menu_sample.py
  jsk_rviz_plugins/scripts/overlay_menu_bridge.py
  jsk_rviz_plugins/src/overlay_menu_display.cpp
  jsk_rviz_plugins/src/overlay_menu_display.h
Labels: feature

#786 [jsk_rviz_plugins] add warn for deprecated jsk_rviz_plugins/PoseArrayDisplay
  jsk_rviz_plugins/src/pose_array_display.cpp
Labels: bug
